#!/bin/env bash
# Function to display subdomain information
display_info() {
  local domain="$1"
  local subdomain="$2"

  # Define subdomains and their corresponding IP addresses
  declare -A subdomains
  subdomains["www"]="lb-01"
  subdomains["lb-01"]="lb-01"
  subdomains["web-01"]="web-01"
  subdomains["web-02"]="web-02"

  # Check if the provided subdomain is in the list
  if [ -n "$subdomain" ] && [ -n "${subdomains[$subdomain]}" ]; then
    echo "The subdomain $subdomain is a A record and points to ${subdomains[$subdomain]} IP address."
  else
    for sub in "${!subdomains[@]}"; do
      echo "The subdomain $sub is a A record and points to ${subdomains[$sub]} IP address."
    done
  fi
}

# Check the number of arguments
if [ $# -lt 1 ]; then
  echo "Usage: $0 DOMAIN [SUBDOMAIN]"
  exit 1
fi

# Assign the domain and subdomain from arguments
domain="yourdelight.tech"
subdomain="$2"

# Call the display_info function
display_info "$domain" "$subdomain"
