#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
server_config=\
'
frontend yourdelight.tech
        bind 0:80
        mode http
        default_backend yourdelight.tech-backend

backend yourdelight.tech-backend
        balance roundrobin
        server 219880-web-01 52.90.22.175:80 check 
        server 219880-web-02 107.22.142.79:80 check
'
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAproxy service
sudo service haproxy restart
